const CONSTANTS = {
  MAX_FILE_SIZE: 8388608,
  MIN_CHANNEL_TITLE_LENGTH: 3,
  MAX_CHANNEL_TITLE_LENGTH: 32,
  MIN_USERNAME_LENGTH: 3,
  MAX_USERNAME_LENGTH: 32,
  MIN_CHAT_TITLE_LENGTH: 3,
  MAX_CHAT_TITLE_LENGTH: 32,
  GET_HISTORY_LIMIT: 50,
  SCROLL_TO_SHOW_SCROLL_BUTTON: 2000,
  MESSAGE_LAYOUT_SETTINGS: {
    CHAR_WIDTH: 7.7,
    LINE_HEIGHT: 21,
    PADDING: 10,
    EMOJI_WIDTH: 24.72,
  },
  VIRTUALIZE_PADDING: 200,
  SHORT_MESSAGE_OFFSET_TIME: 30 * 1000,
  MAX_ATTACHMENTS_COUNT: 3,
  VERSION: '0.2.0',
};

export default CONSTANTS;
