name: Create test build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package dependencies
        run: npm ci
      - name: Create test build
        run: npm run build
        env:
          # Just testing values for build
          CI: false
          REACT_APP_HOST_URL: http://localhost:3000
          REACT_APP_API_URL: http://localhost:3001/api
          REACT_APP_ACCESS_TOKEN_LS_FIELD: access
          REACT_APP_SIGNUP_PAGE_ROUTE: /signup.html
